// Decompiled with JetBrains decompiler
// Type: Ionic.Zlib.Tree
// Assembly: Stardew Valley, Version=1.5.6.22018, Culture=neutral, PublicKeyToken=null
// MVID: BEBB6D18-4941-4529-AC12-B54F0C61CC20
// Assembly location: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Stardew Valley.dll

using System;

namespace Ionic.Zlib
{
  internal sealed class Tree
  {
    private static readonly int HEAP_SIZE = 2 * InternalConstants.L_CODES + 1;
    internal static readonly int[] ExtraLengthBits = new int[29]
    {
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      2,
      2,
      2,
      2,
      3,
      3,
      3,
      3,
      4,
      4,
      4,
      4,
      5,
      5,
      5,
      5,
      0
    };
    internal static readonly int[] ExtraDistanceBits = new int[30]
    {
      0,
      0,
      0,
      0,
      1,
      1,
      2,
      2,
      3,
      3,
      4,
      4,
      5,
      5,
      6,
      6,
      7,
      7,
      8,
      8,
      9,
      9,
      10,
      10,
      11,
      11,
      12,
      12,
      13,
      13
    };
    internal static readonly int[] extra_blbits = new int[19]
    {
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      2,
      3,
      7
    };
    internal static readonly sbyte[] bl_order = new sbyte[19]
    {
      (sbyte) 16,
      (sbyte) 17,
      (sbyte) 18,
      (sbyte) 0,
      (sbyte) 8,
      (sbyte) 7,
      (sbyte) 9,
      (sbyte) 6,
      (sbyte) 10,
      (sbyte) 5,
      (sbyte) 11,
      (sbyte) 4,
      (sbyte) 12,
      (sbyte) 3,
      (sbyte) 13,
      (sbyte) 2,
      (sbyte) 14,
      (sbyte) 1,
      (sbyte) 15
    };
    internal const int Buf_size = 16;
    private static readonly sbyte[] _dist_code = new sbyte[512]
    {
      (sbyte) 0,
      (sbyte) 1,
      (sbyte) 2,
      (sbyte) 3,
      (sbyte) 4,
      (sbyte) 4,
      (sbyte) 5,
      (sbyte) 5,
      (sbyte) 6,
      (sbyte) 6,
      (sbyte) 6,
      (sbyte) 6,
      (sbyte) 7,
      (sbyte) 7,
      (sbyte) 7,
      (sbyte) 7,
      (sbyte) 8,
      (sbyte) 8,
      (sbyte) 8,
      (sbyte) 8,
      (sbyte) 8,
      (sbyte) 8,
      (sbyte) 8,
      (sbyte) 8,
      (sbyte) 9,
      (sbyte) 9,
      (sbyte) 9,
      (sbyte) 9,
      (sbyte) 9,
      (sbyte) 9,
      (sbyte) 9,
      (sbyte) 9,
      (sbyte) 10,
      (sbyte) 10,
      (sbyte) 10,
      (sbyte) 10,
      (sbyte) 10,
      (sbyte) 10,
      (sbyte) 10,
      (sbyte) 10,
      (sbyte) 10,
      (sbyte) 10,
      (sbyte) 10,
      (sbyte) 10,
      (sbyte) 10,
      (sbyte) 10,
      (sbyte) 10,
      (sbyte) 10,
      (sbyte) 11,
      (sbyte) 11,
      (sbyte) 11,
      (sbyte) 11,
      (sbyte) 11,
      (sbyte) 11,
      (sbyte) 11,
      (sbyte) 11,
      (sbyte) 11,
      (sbyte) 11,
      (sbyte) 11,
      (sbyte) 11,
      (sbyte) 11,
      (sbyte) 11,
      (sbyte) 11,
      (sbyte) 11,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 0,
      (sbyte) 0,
      (sbyte) 16,
      (sbyte) 17,
      (sbyte) 18,
      (sbyte) 18,
      (sbyte) 19,
      (sbyte) 19,
      (sbyte) 20,
      (sbyte) 20,
      (sbyte) 20,
      (sbyte) 20,
      (sbyte) 21,
      (sbyte) 21,
      (sbyte) 21,
      (sbyte) 21,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 28,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29,
      (sbyte) 29
    };
    internal static readonly sbyte[] LengthCode = new sbyte[256]
    {
      (sbyte) 0,
      (sbyte) 1,
      (sbyte) 2,
      (sbyte) 3,
      (sbyte) 4,
      (sbyte) 5,
      (sbyte) 6,
      (sbyte) 7,
      (sbyte) 8,
      (sbyte) 8,
      (sbyte) 9,
      (sbyte) 9,
      (sbyte) 10,
      (sbyte) 10,
      (sbyte) 11,
      (sbyte) 11,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 12,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 13,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 14,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 15,
      (sbyte) 16,
      (sbyte) 16,
      (sbyte) 16,
      (sbyte) 16,
      (sbyte) 16,
      (sbyte) 16,
      (sbyte) 16,
      (sbyte) 16,
      (sbyte) 17,
      (sbyte) 17,
      (sbyte) 17,
      (sbyte) 17,
      (sbyte) 17,
      (sbyte) 17,
      (sbyte) 17,
      (sbyte) 17,
      (sbyte) 18,
      (sbyte) 18,
      (sbyte) 18,
      (sbyte) 18,
      (sbyte) 18,
      (sbyte) 18,
      (sbyte) 18,
      (sbyte) 18,
      (sbyte) 19,
      (sbyte) 19,
      (sbyte) 19,
      (sbyte) 19,
      (sbyte) 19,
      (sbyte) 19,
      (sbyte) 19,
      (sbyte) 19,
      (sbyte) 20,
      (sbyte) 20,
      (sbyte) 20,
      (sbyte) 20,
      (sbyte) 20,
      (sbyte) 20,
      (sbyte) 20,
      (sbyte) 20,
      (sbyte) 20,
      (sbyte) 20,
      (sbyte) 20,
      (sbyte) 20,
      (sbyte) 20,
      (sbyte) 20,
      (sbyte) 20,
      (sbyte) 20,
      (sbyte) 21,
      (sbyte) 21,
      (sbyte) 21,
      (sbyte) 21,
      (sbyte) 21,
      (sbyte) 21,
      (sbyte) 21,
      (sbyte) 21,
      (sbyte) 21,
      (sbyte) 21,
      (sbyte) 21,
      (sbyte) 21,
      (sbyte) 21,
      (sbyte) 21,
      (sbyte) 21,
      (sbyte) 21,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 22,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 23,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 24,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 25,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 26,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 27,
      (sbyte) 28
    };
    internal static readonly int[] LengthBase = new int[29]
    {
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      10,
      12,
      14,
      16,
      20,
      24,
      28,
      32,
      40,
      48,
      56,
      64,
      80,
      96,
      112,
      128,
      160,
      192,
      224,
      0
    };
    internal static readonly int[] DistanceBase = new int[30]
    {
      0,
      1,
      2,
      3,
      4,
      6,
      8,
      12,
      16,
      24,
      32,
      48,
      64,
      96,
      128,
      192,
      256,
      384,
      512,
      768,
      1024,
      1536,
      2048,
      3072,
      4096,
      6144,
      8192,
      12288,
      16384,
      24576
    };
    internal short[] dyn_tree;
    internal int max_code;
    internal StaticTree staticTree;

    /// <summary>Map from a distance to a distance code.</summary>
    /// <remarks>
    /// No side effects. _dist_code[256] and _dist_code[257] are never used.
    /// </remarks>
    internal static int DistanceCode(int dist) => dist >= 256 ? (int) Tree._dist_code[256 + SharedUtils.URShift(dist, 7)] : (int) Tree._dist_code[dist];

    internal void gen_bitlen(DeflateManager s)
    {
      short[] dynTree = this.dyn_tree;
      short[] treeCodes = this.staticTree.treeCodes;
      int[] extraBits = this.staticTree.extraBits;
      int extraBase = this.staticTree.extraBase;
      int maxLength = this.staticTree.maxLength;
      int num1 = 0;
      for (int index = 0; index <= InternalConstants.MAX_BITS; ++index)
        s.bl_count[index] = (short) 0;
      dynTree[s.heap[s.heap_max] * 2 + 1] = (short) 0;
      int index1;
      for (index1 = s.heap_max + 1; index1 < Tree.HEAP_SIZE; ++index1)
      {
        int num2 = s.heap[index1];
        int index2 = (int) dynTree[(int) dynTree[num2 * 2 + 1] * 2 + 1] + 1;
        if (index2 > maxLength)
        {
          index2 = maxLength;
          ++num1;
        }
        dynTree[num2 * 2 + 1] = (short) index2;
        if (num2 <= this.max_code)
        {
          ++s.bl_count[index2];
          int num3 = 0;
          if (num2 >= extraBase)
            num3 = extraBits[num2 - extraBase];
          short num4 = dynTree[num2 * 2];
          s.opt_len += (int) num4 * (index2 + num3);
          if (treeCodes != null)
            s.static_len += (int) num4 * ((int) treeCodes[num2 * 2 + 1] + num3);
        }
      }
      if (num1 == 0)
        return;
      do
      {
        int index3 = maxLength - 1;
        while (s.bl_count[index3] == (short) 0)
          --index3;
        --s.bl_count[index3];
        s.bl_count[index3 + 1] = (short) ((int) s.bl_count[index3 + 1] + 2);
        --s.bl_count[maxLength];
        num1 -= 2;
      }
      while (num1 > 0);
      for (int index4 = maxLength; index4 != 0; --index4)
      {
        int num5 = (int) s.bl_count[index4];
        while (num5 != 0)
        {
          int num6 = s.heap[--index1];
          if (num6 <= this.max_code)
          {
            if ((int) dynTree[num6 * 2 + 1] != index4)
            {
              s.opt_len = (int) ((long) s.opt_len + ((long) index4 - (long) dynTree[num6 * 2 + 1]) * (long) dynTree[num6 * 2]);
              dynTree[num6 * 2 + 1] = (short) index4;
            }
            --num5;
          }
        }
      }
    }

    internal void build_tree(DeflateManager s)
    {
      short[] dynTree = this.dyn_tree;
      short[] treeCodes = this.staticTree.treeCodes;
      int elems = this.staticTree.elems;
      int max_code = -1;
      s.heap_len = 0;
      s.heap_max = Tree.HEAP_SIZE;
      for (int index = 0; index < elems; ++index)
      {
        if (dynTree[index * 2] != (short) 0)
        {
          s.heap[++s.heap_len] = max_code = index;
          s.depth[index] = (sbyte) 0;
        }
        else
          dynTree[index * 2 + 1] = (short) 0;
      }
      while (s.heap_len < 2)
      {
        int[] heap = s.heap;
        int index1 = ++s.heap_len;
        int num1;
        if (max_code >= 2)
          num1 = 0;
        else
          max_code = num1 = max_code + 1;
        int num2 = num1;
        heap[index1] = num1;
        int index2 = num2;
        dynTree[index2 * 2] = (short) 1;
        s.depth[index2] = (sbyte) 0;
        --s.opt_len;
        if (treeCodes != null)
          s.static_len -= (int) treeCodes[index2 * 2 + 1];
      }
      this.max_code = max_code;
      for (int k = s.heap_len / 2; k >= 1; --k)
        s.pqdownheap(dynTree, k);
      int index3 = elems;
      do
      {
        int index4 = s.heap[1];
        s.heap[1] = s.heap[s.heap_len--];
        s.pqdownheap(dynTree, 1);
        int index5 = s.heap[1];
        s.heap[--s.heap_max] = index4;
        s.heap[--s.heap_max] = index5;
        dynTree[index3 * 2] = (short) ((int) dynTree[index4 * 2] + (int) dynTree[index5 * 2]);
        s.depth[index3] = (sbyte) ((int) Math.Max((byte) s.depth[index4], (byte) s.depth[index5]) + 1);
        dynTree[index4 * 2 + 1] = dynTree[index5 * 2 + 1] = (short) index3;
        s.heap[1] = index3++;
        s.pqdownheap(dynTree, 1);
      }
      while (s.heap_len >= 2);
      s.heap[--s.heap_max] = s.heap[1];
      this.gen_bitlen(s);
      Tree.gen_codes(dynTree, max_code, s.bl_count);
    }

    internal static void gen_codes(short[] tree, int max_code, short[] bl_count)
    {
      short[] numArray = new short[InternalConstants.MAX_BITS + 1];
      short num = 0;
      for (int index = 1; index <= InternalConstants.MAX_BITS; ++index)
        numArray[index] = num = (short) ((int) num + (int) bl_count[index - 1] << 1);
      for (int index = 0; index <= max_code; ++index)
      {
        int len = (int) tree[index * 2 + 1];
        if (len != 0)
          tree[index * 2] = (short) Tree.bi_reverse((int) numArray[len]++, len);
      }
    }

    internal static int bi_reverse(int code, int len)
    {
      int num1 = 0;
      do
      {
        int num2 = num1 | code & 1;
        code >>= 1;
        num1 = num2 << 1;
      }
      while (--len > 0);
      return num1 >> 1;
    }
  }
}
